### ISSUE TITLE
Newest AvatarLoader 1.3.0 does not work with the current latest release of the 'Core' package 1.2.0

### ISSUE THREAD

**Issue by aherbig** [readyplayerme/rpm-unity-sdk-avatar-loader#91]
**Describe the bug**
AvatarLoader can not build successfully because the core package does not provide the required methods used by the avatarloader.
Especially the 'GetFolderSizeInMb' from the DirectoryUtil

**To Reproduce**
1. Create a project that uses the 1.2.0 version of the core-package, and 1.2.0 of the avatar loader
2. Confirm the update prompt to update the avatarloader to 1.3.0
3. Project can not build due to missing method

**Expected behavior**
Have a released version of the core package that gets updated too.

**Screenshots**
![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-loader/assets/16133886/b9185bf1-f36a-44d7-9979-715192375e6b)

**Comment by aherbig** [comment]
Can be fixed by importing the core-package from this url:
"com.readyplayerme.core": "https://github.com/readyplayerme/rpm-unity-sdk-core.git#release/v1.3.0",

**Comment by srcnalt** [comment]
Hi @aherbig there is an issue with auto update for core it seems, you can update Core through Package Manager at the moment.

**Comment by rYuuk** [comment]
Apologies for any confusion caused. We have successfully added the Core release v1.3.0.

**Comment by aherbig** [comment]
No worries. Thanks for the quick fix :)
